// =============================================================================
// Swing Terminal — Strategy Engine
// -----------------------------------------------------------------------------
// VERBATIM extraction of the original engine block from
// /legacy/swing_terminal_4-1.html (lines 1356–2992 of that file).
//
// The body of every function in this file is character-for-character identical
// to the original. The only changes are:
//
//   1. The `<script>` HTML wrapper is removed.
//   2. `fetchFMPData` has been moved to /src/data/fmp.js (it depends on `state`
//      and `fetchWithTimeout`, neither of which exist in this pure-math module).
//      The strategies that consume FMP data (`evaluatePEAD`, `evaluateInsiderCluster`,
//      `evaluateAnalystUpgrade`) already accept `fmpData` as a parameter, so they
//      stay here unchanged.
//   3. An `export` block at the bottom exposes every public function as ESM.
//
// Do NOT edit this file. If a strategy needs to evolve, write a new function in
// /src/strategy/extensions.js and compose it. The /tests/engine-parity.mjs suite
// pins these functions' outputs to a fixture so accidental edits surface fast.
// =============================================================================

// ---------- Indicator primitives ----------

function sma(values, period) {
  const out = new Array(values.length).fill(null);
  let sum = 0;
  for (let i = 0; i < values.length; i++) {
    sum += values[i];
    if (i >= period) sum -= values[i - period];
    if (i >= period - 1) out[i] = sum / period;
  }
  return out;
}

function ema(values, period) {
  const out = new Array(values.length).fill(null);
  if (values.length < period) return out;
  // Seed with SMA of first `period` values
  let seed = 0;
  for (let i = 0; i < period; i++) seed += values[i];
  out[period - 1] = seed / period;
  const k = 2 / (period + 1);
  for (let i = period; i < values.length; i++) {
    out[i] = values[i] * k + out[i - 1] * (1 - k);
  }
  return out;
}

// True Range and Wilder ATR (matches TradingView default)
function atr(high, low, close, period) {
  const n = close.length;
  const tr = new Array(n).fill(null);
  for (let i = 0; i < n; i++) {
    if (i === 0) {
      tr[i] = high[i] - low[i];
    } else {
      const a = high[i] - low[i];
      const b = Math.abs(high[i] - close[i - 1]);
      const c = Math.abs(low[i] - close[i - 1]);
      tr[i] = Math.max(a, b, c);
    }
  }
  const out = new Array(n).fill(null);
  if (n < period) return out;
  // Seed with simple average of first `period` TRs
  let seed = 0;
  for (let i = 0; i < period; i++) seed += tr[i];
  out[period - 1] = seed / period;
  for (let i = period; i < n; i++) {
    out[i] = (out[i - 1] * (period - 1) + tr[i]) / period;
  }
  return out;
}

function rollingMax(values, period) {
  const out = new Array(values.length).fill(null);
  for (let i = period - 1; i < values.length; i++) {
    let m = -Infinity;
    for (let j = i - period + 1; j <= i; j++) m = Math.max(m, values[j]);
    out[i] = m;
  }
  return out;
}

function rollingMin(values, period) {
  const out = new Array(values.length).fill(null);
  for (let i = period - 1; i < values.length; i++) {
    let m = Infinity;
    for (let j = i - period + 1; j <= i; j++) m = Math.min(m, values[j]);
    out[i] = m;
  }
  return out;
}

function rollingMean(values, period) { return sma(values, period); }

function rsi(close, period) {
  const out = new Array(close.length).fill(null);
  if (close.length < period + 1) return out;
  let avgGain = 0, avgLoss = 0;
  for (let i = 1; i <= period; i++) {
    const d = close[i] - close[i - 1];
    if (d > 0) avgGain += d; else avgLoss -= d;
  }
  avgGain /= period; avgLoss /= period;
  out[period] = avgLoss === 0 ? 100 : 100 - 100 / (1 + avgGain / avgLoss);
  for (let i = period + 1; i < close.length; i++) {
    const d = close[i] - close[i - 1];
    avgGain = (avgGain * (period - 1) + (d > 0 ? d : 0)) / period;
    avgLoss = (avgLoss * (period - 1) + (d < 0 ? -d : 0)) / period;
    out[i] = avgLoss === 0 ? 100 : 100 - 100 / (1 + avgGain / avgLoss);
  }
  return out;
}

function pctReturn(values, lookback) {
  const out = new Array(values.length).fill(null);
  for (let i = lookback; i < values.length; i++) {
    if (values[i - lookback] > 0) {
      out[i] = (values[i] / values[i - lookback]) - 1;
    }
  }
  return out;
}

// ---------- L1 quality + L3 setup detection ----------

// bars: array of {date, open, high, low, close, volume}, sorted oldest -> newest
// spyBars: same shape, used for relative strength
// idx: bar index to evaluate ("today" = the most recent COMPLETED bar)
function evaluateSetup(bars, spyBars, idx, cfg = {}) {
  const reasons = []; // why pass / why fail
  const result = {
    qualifies_L1: false,
    setup_armed_L3: false,
    confirmation_bar: false,
    reasons,
    metrics: {}
  };
  if (idx < 220) { reasons.push('Insufficient history (<220 bars)'); return result; }

  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const vol   = bars.map(b => b.volume);

  const sma200 = sma(close, 200);
  const sma50  = sma(close,  50);
  const ema20  = ema(close,  20);
  const atr14  = atr(high, low, close, 14);
  const high20 = rollingMax(high, 20);
  const high52w = rollingMax(high, 252);
  const advUsd20 = (function () {
    const out = new Array(close.length).fill(null);
    for (let i = 19; i < close.length; i++) {
      let s = 0;
      for (let j = i - 19; j <= i; j++) s += close[j] * vol[j];
      out[i] = s / 20;
    }
    return out;
  })();

  const c = close[idx];
  const m200 = sma200[idx], m50 = sma50[idx];
  const e20 = ema20[idx], a14 = atr14[idx];
  const h52 = high52w[idx];
  const adv = advUsd20[idx];

  result.metrics = {
    close: c, sma200: m200, sma50: m50, ema20: e20, atr14: a14,
    high52w: h52, adv_usd_20d: adv,
    pct_below_52w_high: h52 ? (1 - c / h52) * 100 : null
  };

  // L1 quality
  let pass = true;
  if (!(c > (cfg.minPrice ?? 20) && c < (cfg.maxPrice ?? 1500))) { reasons.push(`Price outside [${cfg.minPrice ?? 20}, ${cfg.maxPrice ?? 1500}]`); pass = false; }
  if (!(adv && adv > (cfg.minAdv ?? 20_000_000))) { reasons.push(`20d ADV ${(adv/1e6).toFixed(1)}M < ${((cfg.minAdv ?? 20_000_000)/1e6).toFixed(0)}M`); pass = false; }
  if (!(c > m200))                              { reasons.push(`Close ${c.toFixed(2)} not above 200-SMA ${m200?.toFixed(2)}`); pass = false; }
  if (!(m50 > m200))                            { reasons.push(`50-SMA ${m50?.toFixed(2)} not > 200-SMA ${m200?.toFixed(2)}`); pass = false; }
  const pctFromHigh = h52 ? (1 - c / h52) * 100 : 999;
  if (!(pctFromHigh <= 15))                     { reasons.push(`${pctFromHigh.toFixed(1)}% below 52w high (>15%)`); pass = false; }

  // 1-month RS vs SPY
  if (spyBars && spyBars.length > idx) {
    const spyClose = spyBars.map(b => b.close);
    const stockRet = (close[idx] / close[idx - 21]) - 1;
    const spyRet   = (spyClose[idx] / spyClose[idx - 21]) - 1;
    result.metrics.ret_1m = stockRet;
    result.metrics.spy_ret_1m = spyRet;
    if (!(stockRet > spyRet))                   { reasons.push(`1m return ${(stockRet*100).toFixed(2)}% <= SPY ${(spyRet*100).toFixed(2)}%`); pass = false; }
  }

  result.qualifies_L1 = pass;
  if (!pass) return result;

  // L3 setup
  // Was there a new 20-day high in the last 10 bars?
  let highDayIdx = -1, highDayValue = -Infinity;
  for (let k = idx - 10; k <= idx; k++) {
    if (k < 19) continue;
    if (high[k] >= high20[k] - 1e-9) { // bar made/touched a 20-day high that day
      if (high[k] > highDayValue) { highDayValue = high[k]; highDayIdx = k; }
    }
  }
  if (highDayIdx < 0) { reasons.push('No new 20-day high in last 10 bars'); return result; }

  // Pullback from highDayIdx to idx must be 2-5 bars
  const pullbackBars = idx - highDayIdx;
  result.metrics.pullback_bars = pullbackBars;
  if (pullbackBars < 2 || pullbackBars > 5) {
    reasons.push(`Pullback length ${pullbackBars} bars outside [2,5]`);
    return result;
  }

  // Pullback low above 50-SMA (closing basis)
  let pullbackLow = Infinity, pullbackLowIdx = highDayIdx;
  for (let k = highDayIdx + 1; k <= idx; k++) {
    if (close[k] < pullbackLow) { pullbackLow = close[k]; pullbackLowIdx = k; }
  }
  if (!(pullbackLow > sma50[pullbackLowIdx])) {
    reasons.push(`Pullback close low ${pullbackLow.toFixed(2)} broke 50-SMA ${sma50[pullbackLowIdx]?.toFixed(2)}`);
    return result;
  }
  result.metrics.pullback_low = pullbackLow;

  // Within 1.0 x ATR of 20-EMA at any point during the pullback
  let touched20EMA = false;
  for (let k = highDayIdx; k <= idx; k++) {
    if (low[k] <= ema20[k] + 1e-9) { touched20EMA = true; break; }
    if (Math.abs(close[k] - ema20[k]) <= atr14[k]) { touched20EMA = true; break; }
  }
  if (!touched20EMA) {
    reasons.push('Pullback never came within 1×ATR of 20-EMA');
    return result;
  }

  // Pullback retracement 30-60% of the prior leg
  // Leg = from prior swing low (lowest close in 20 bars before highDayIdx) up to high20 high
  let legStartIdx = Math.max(0, highDayIdx - 20), legStartVal = Infinity;
  for (let k = Math.max(0, highDayIdx - 20); k < highDayIdx; k++) {
    if (low[k] < legStartVal) { legStartVal = low[k]; legStartIdx = k; }
  }
  const legHigh = high[highDayIdx];
  const legRange = legHigh - legStartVal;
  const retracePct = legRange > 0 ? ((legHigh - pullbackLow) / legRange) * 100 : 0;
  result.metrics.retrace_pct = retracePct;
  if (!(retracePct >= 30 && retracePct <= 60)) {
    reasons.push(`Retracement ${retracePct.toFixed(1)}% outside [30, 60]`);
    return result;
  }

  result.setup_armed_L3 = true;

  // Confirmation bar = the bar at idx
  const priorHigh = high[idx - 1];
  const closeAbovePriorHigh = close[idx] > priorHigh;
  const range = high[idx] - low[idx];
  const closePos = range > 0 ? (close[idx] - low[idx]) / range : 0;
  const avgVol20 = (function () { let s = 0; for (let k = idx - 19; k <= idx; k++) s += vol[k]; return s / 20; })();
  const volMult = avgVol20 ? vol[idx] / avgVol20 : 0;
  result.metrics.close_position_in_range = closePos;
  result.metrics.volume_multiple = volMult;

  if (closeAbovePriorHigh && closePos >= 0.5 && volMult >= 1.0) {
    result.confirmation_bar = true;
    // Compute trade plan
    const entryTrigger = high[idx] * 1.001;
    const stopDistance = 1.5 * atr14[idx];
    result.trade_plan = {
      entry_trigger: entryTrigger,
      initial_stop_estimate: entryTrigger - stopDistance,
      first_target_estimate: entryTrigger + 2 * stopDistance,
      atr14: atr14[idx]
    };
    reasons.push('All L1+L3 conditions met; confirmation bar printed');
  } else {
    const why = [];
    if (!closeAbovePriorHigh) why.push('close not > prior high');
    if (closePos < 0.5)        why.push(`close in lower half of range (pos=${closePos.toFixed(2)})`);
    if (volMult < 1.0)         why.push(`volume ${volMult.toFixed(2)}× < 1.0× avg`);
    reasons.push('Setup armed but no confirmation: ' + why.join(', '));
  }

  return result;
}

// ---------- L2 regime ----------

function regimeCheck(spyBars, vixBars, breadthMmfi /* manual numeric, optional */, opts = {}) {
  const out = { tradeable: false, go_to_cash: false, checks: [], details: {} };
  const vixThreshold = opts.vixThreshold ?? 25;
  const vixPanic     = opts.vixPanic     ?? 28;
  const indexLabel   = opts.indexLabel   ?? 'SPY';
  if (!spyBars || spyBars.length < 220) {
    out.checks.push({ name: `${indexLabel} history`, pass: false, note: 'Need 220+ daily bars' });
    return out;
  }
  const close = spyBars.map(b => b.close);
  const sma50 = sma(close, 50);
  const sma200 = sma(close, 200);
  const i = close.length - 1;
  const spyClose = close[i];
  const spy50 = sma50[i], spy200 = sma200[i];
  out.details.spy_close = spyClose;
  out.details.spy_50sma = spy50;
  out.details.spy_200sma = spy200;

  const a = spyClose > spy200; out.checks.push({ name: `${indexLabel} > 200-SMA`, pass: a, note: `${spyClose.toFixed(2)} vs ${spy200.toFixed(2)}` });
  const b = spyClose > spy50;  out.checks.push({ name: `${indexLabel} > 50-SMA`,  pass: b, note: `${spyClose.toFixed(2)} vs ${spy50.toFixed(2)}` });

  let cPass = null, cNote = '(no VIX data)';
  if (vixBars && vixBars.length) {
    const vClose = vixBars[vixBars.length - 1].close;
    out.details.vix = vClose;
    cPass = vClose < vixThreshold;
    cNote = `VIX ${vClose.toFixed(2)} < ${vixThreshold}`;
  }
  out.checks.push({ name: `VIX < ${vixThreshold}`, pass: cPass, note: cNote });

  let dPass = null, dNote = '(MMFI not provided)';
  if (typeof breadthMmfi === 'number') {
    out.details.mmfi = breadthMmfi;
    dPass = breadthMmfi > 50;
    dNote = `MMFI ${breadthMmfi} > 50`;
  }
  out.checks.push({ name: 'Breadth (MMFI > 50%)', pass: dPass, note: dNote });

  const passed = out.checks.filter(c => c.pass === true).length;
  const failed = out.checks.filter(c => c.pass === false).length;
  out.tradeable = passed >= 3 && a && b; // SPY trend gates are mandatory
  out.go_to_cash = !a || (cPass === false && vixBars && vixBars[vixBars.length - 1].close > vixPanic) || failed >= 2;
  return out;
}

// ---------- Bullish FVG (Fair Value Gap) on monthly chart ----------
// A 3-bar imbalance: bar[t-2].high < bar[t].low forms a "gap" zone between those two prices.
// In an uptrend, a price retrace BACK into that zone often acts as support — that's the trade.
// This is a slow, patient, higher-timeframe signal that complements the daily 20-EMA system.

function aggregateMonthly(dailyBars) {
  if (!dailyBars || !dailyBars.length) return [];
  const out = [];
  let cur = null;
  for (const b of dailyBars) {
    const ym = b.date.slice(0, 7); // YYYY-MM
    if (!cur || cur.ym !== ym) {
      if (cur) out.push(cur);
      cur = { ym, date: b.date, open: b.open, high: b.high, low: b.low, close: b.close, volume: b.volume || 0 };
    } else {
      cur.high = Math.max(cur.high, b.high);
      cur.low = Math.min(cur.low, b.low);
      cur.close = b.close;
      cur.volume += b.volume || 0;
      cur.date = b.date;
    }
  }
  if (cur) out.push(cur);
  return out;
}

function findBullishFVGs(monthlyBars, lookback = 36) {
  const fvgs = [];
  const start = Math.max(2, monthlyBars.length - lookback);
  for (let i = start; i < monthlyBars.length; i++) {
    const a = monthlyBars[i - 2], c = monthlyBars[i];
    if (a.high < c.low) {
      fvgs.push({
        idx: i,
        zone_low: a.high,
        zone_high: c.low,
        mid: (a.high + c.low) / 2,
        size_pct: ((c.low - a.high) / a.high) * 100,
        formed_date: c.date
      });
    }
  }
  return fvgs;
}

function evaluateFVGRetest(dailyBars) {
  const monthly = aggregateMonthly(dailyBars);
  if (monthly.length < 24) return { detected: false, reason: 'insufficient monthly history (<24 months)' };
  const mClose = monthly.map(b => b.close);
  const ma12 = sma(mClose, 12);
  const last = monthly.length - 1;
  if (!(mClose[last] > (ma12[last] || Infinity))) {
    return { detected: false, reason: 'monthly close below 12-month MA — not in monthly uptrend' };
  }
  // Find unfilled bullish FVGs below current price
  const fvgs = findBullishFVGs(monthly, 36);
  const unfilled = fvgs.filter(f =>
    f.idx <= last - 1 &&            // not the current bar's own pattern
    f.zone_high < mClose[last] &&    // zone is below price (still a support, not resistance)
    f.zone_low > (ma12[last] || 0)   // zone is above the 12-month MA (still in trend territory)
  );
  if (!unfilled.length) return { detected: false, reason: 'no unfilled bullish FVG zones below current price' };
  // Sort by closest to current price (most recent retest opportunity)
  unfilled.sort((a, b) => b.zone_high - a.zone_high);
  const cur = monthly[last];
  for (const f of unfilled) {
    // Tag a "retest in progress" if current month's low penetrated within 3% below the zone
    if (cur.low <= f.zone_high && cur.low >= f.zone_low * 0.97) {
      const reactionOk = cur.close > f.mid;
      return {
        detected: true,
        zone_low: f.zone_low, zone_high: f.zone_high, zone_mid: f.mid,
        zone_size_pct: f.size_pct,
        formed_date: f.formed_date,
        current_low: cur.low, current_close: cur.close,
        bullish_reaction: reactionOk,
        reason: reactionOk
          ? `Retesting bullish FVG ${f.zone_low.toFixed(2)}–${f.zone_high.toFixed(2)} (formed ${f.formed_date}); bullish reaction (close > mid)`
          : `Retesting bullish FVG ${f.zone_low.toFixed(2)}–${f.zone_high.toFixed(2)} (formed ${f.formed_date}); awaiting bullish reaction`
      };
    }
  }
  // Note nearest unfilled zone for context
  const nearest = unfilled[0];
  const distancePct = ((mClose[last] - nearest.zone_high) / mClose[last]) * 100;
  return {
    detected: false,
    nearest_zone: { low: nearest.zone_low, high: nearest.zone_high, formed_date: nearest.formed_date },
    distance_pct: distancePct,
    reason: `nearest unfilled FVG ${nearest.zone_low.toFixed(2)}–${nearest.zone_high.toFixed(2)} is ${distancePct.toFixed(1)}% below price`
  };
}

// ---------- Quality Dip scanner (mean reversion on quality) ----------
// Inspired by the "buy the dip on liquid blue chips" pattern. Filters out falling knives:
//   - Down 10–25% from 52w high (real dip, not catastrophic breakdown)
//   - Still above 200-day SMA (long-term trend intact)
//   - Last 10-day low not breaking the prior 10-day low (stabilization)
//   - Close > 10-day SMA (short-term reversal showing)
//   - Recent 3-day vol vs 20-day avg ≥ 1.0 (institutional accumulation)
function evaluateQualityDip(bars, idx) {
  if (idx < 252) return { detected: false, reason: 'insufficient history (<252 bars)' };
  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const vol   = bars.map(b => b.volume);
  const c = close[idx];
  const sma200 = sma(close, 200)[idx];
  const sma10  = sma(close, 10)[idx];
  const high52 = rollingMax(high, 252)[idx];
  const a14    = atr(high, low, close, 14)[idx];
  if (!high52 || !sma200 || !sma10 || !a14) return { detected: false, reason: 'indicator warmup incomplete' };

  const fromHi = (1 - c / high52) * 100;
  if (fromHi < 10) return { detected: false, reason: `only ${fromHi.toFixed(1)}% off 52w high — too shallow (need ≥10%)` };
  if (fromHi > 30) return { detected: false, reason: `${fromHi.toFixed(1)}% off 52w high — too deep, may be broken` };
  if (c < sma200)  return { detected: false, reason: `close ${c.toFixed(2)} below 200-SMA ${sma200.toFixed(2)} — long-term trend broken` };

  // Stabilization: last 10-day low ≥ 98% of prior 10-day low
  const last10Low = Math.min(...low.slice(idx - 9, idx + 1));
  const prior10Low = Math.min(...low.slice(idx - 19, idx - 9));
  if (last10Low < prior10Low * 0.98) {
    return { detected: false, reason: 'still making lower lows (falling knife)' };
  }
  // Reversal: close above 10-SMA
  if (c < sma10) return { detected: false, reason: `close below 10-SMA ${sma10.toFixed(2)} — no reversal yet` };

  // Volume confirmation
  const vol3  = (vol[idx] + vol[idx-1] + vol[idx-2]) / 3;
  const vol20 = vol.slice(idx - 19, idx + 1).reduce((a, b) => a + b, 0) / 20;
  const volMult = vol20 ? vol3 / vol20 : 0;
  const volOk = volMult >= 1.0;

  // Trade plan
  const stopRaw = Math.min(last10Low * 0.99, c - 1.5 * a14);
  const target = high52 * 0.97; // recover 97% of 52w high
  const riskPS = c - stopRaw;
  const r_multiple = riskPS > 0 ? (target - c) / riskPS : 0;

  return {
    detected: true,
    pct_below_52w_high: fromHi,
    last_10d_low: last10Low,
    sma10, sma200, atr14: a14,
    volume_multiple: volMult,
    volume_confirmed: volOk,
    trade_plan: {
      entry: c,
      stop: stopRaw,
      target,
      r_multiple,
      atr14: a14
    },
    reason: `${fromHi.toFixed(1)}% off 52w high · above 200-SMA · stabilized · vol ${volMult.toFixed(1)}× ${volOk ? '✓' : '(weak)'}` +
            ` · trade plan: entry ${c.toFixed(2)}, stop ${stopRaw.toFixed(2)}, target ${target.toFixed(2)} (${r_multiple.toFixed(1)}R)`
  };
}

// ---------- Volatility Contraction Pattern (Mark Minervini) ----------
// VCP is one of the highest-probability institutional setups:
// uptrend stock builds a base of 3+ progressively tighter contractions
// while volume dries up, then breaks out on a surge. Pivot = last contraction high.
//
// Detection: divide the last 60-bar base into 3 x 20-bar windows.
// Each window's high-low range % must contract by ≥10% vs. prior window.
// Volume in the late window must be <65% of early window average (dry-up).
// Stock must still be within 8% of the pivot (hasn't broken down).
function evaluateVCP(bars, idx) {
  if (idx < 260) return { detected: false, reason: 'insufficient history (<260 bars)' };
  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const vol   = bars.map(b => b.volume);

  const c    = close[idx];
  const s150 = sma(close, 150)[idx];
  const s200 = sma(close, 200)[idx];
  const h52  = rollingMax(high, 252)[idx];

  if (!s150 || !s200 || !h52) return { detected: false, reason: 'indicator warmup incomplete' };
  if (c < s150 || c < s200)   return { detected: false, reason: 'below 150 or 200-SMA (not in uptrend)' };

  const fromHi = (1 - c / h52) * 100;
  if (fromHi > 25) return { detected: false, reason: `${fromHi.toFixed(1)}% off 52w high — needs ≤25%` };

  // Build 3 windows of 20 bars each (= 60-bar base)
  const WIN = 20;
  const segs = [0, 1, 2].map(i => {
    const start = idx - (3 - i) * WIN;
    const end   = idx - (2 - i) * WIN;
    const h = high.slice(start, end + 1);
    const l = low.slice(start, end + 1);
    const v = vol.slice(start, end + 1);
    const hi = Math.max(...h), lo = Math.min(...l);
    return {
      hi, lo,
      range:  hi > 0 ? ((hi - lo) / hi) * 100 : 0,
      avgVol: v.reduce((a, b) => a + b, 0) / v.length
    };
  });

  // Contracting ranges: each window must shrink vs. previous by ≥10%
  const c1 = segs[1].range < segs[0].range * 0.90;
  const c2 = segs[2].range < segs[1].range * 0.90;
  if (!c1 || !c2) {
    return {
      detected: false,
      reason: `ranges not contracting: ${segs.map(s => s.range.toFixed(1) + '%').join(' → ')}`
    };
  }

  // Stock must be within 8% of the pivot (last window high) — hasn't broken down
  const pivot = segs[2].hi;
  const pctBelowPivot = ((pivot - c) / pivot) * 100;
  if (pctBelowPivot > 8) {
    return { detected: false, reason: `${pctBelowPivot.toFixed(1)}% below pivot — base broken or waiting` };
  }

  // Volume dry-up: late segment avg vol < 65% of early segment avg vol
  const volRatio = segs[0].avgVol > 0 ? segs[2].avgVol / segs[0].avgVol : 1;
  const volDry   = volRatio < 0.65;

  const rangeStr = segs.map(s => s.range.toFixed(1) + '%').join(' → ');
  return {
    detected: true,
    pivot,
    segs,
    pct_below_pivot:   pctBelowPivot,
    pct_below_52w_high: fromHi,
    volume_dry:        volDry,
    vol_ratio:         volRatio,
    reason: `3-contraction VCP · ranges ${rangeStr} · pivot ${pivot.toFixed(2)} ` +
            `(−8 ${pctBelowPivot.toFixed(1)}%) · vol ${volRatio.toFixed(2)}× ${volDry ? '(drying ✓)' : '(not dry ⚠)'}`
  };
}

// ---------- RSI(2) Mean Reversion (Larry Connors) ----------
// The highest documented win-rate pure-price strategy: 75–85% on large caps above 200-SMA.
// Buy when RSI(2) < 10 (extreme oversold on quality stock). Exit when RSI(2) > 70 or close > 5-SMA.
// Documented in "Short-Term Trading Strategies That Work" (Connors & Alvarez, 2008).
// Hold time: 2–7 trading days. Works across US, India, Europe markets.
function evaluateRSI2MeanReversion(bars, idx) {
  if (idx < 220) return { detected: false, reason: 'insufficient history' };
  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const vol   = bars.map(b => b.volume);
  const c = close[idx];

  const s200 = sma(close, 200)[idx];
  const s5   = sma(close, 5)[idx];
  if (!s200 || !s5) return { detected: false, reason: 'indicator warmup incomplete' };
  if (c < s200) return { detected: false, reason: 'below 200-SMA (long-term trend broken)' };

  const rsi2  = rsi(close, 2)[idx];
  const rsi14 = rsi(close, 14)[idx];
  if (rsi2 == null) return { detected: false, reason: 'RSI(2) not available' };
  if (rsi2 >= 10) return { detected: false, reason: `RSI(2) = ${rsi2.toFixed(1)} (need < 10)` };

  const extreme = rsi2 < 5;
  const a14 = atr(high, low, close, 14)[idx];

  // 3-day consecutive close decline check (stronger signal)
  const threeDayDecline = idx >= 3 && close[idx] < close[idx-1] && close[idx-1] < close[idx-2] && close[idx-2] < close[idx-3];

  // Exit target: RSI(2) > 70 or close > 5-SMA (whichever comes first)
  const exitTarget5SMA = s5;

  // Stop: close - 1.5 * ATR(14) or below recent 10-bar low
  const low10 = Math.min(...low.slice(Math.max(0, idx - 9), idx + 1));
  const stopATR = c - 1.5 * (a14 || 0);
  const stop = Math.max(stopATR, low10 * 0.99);

  // Drawdown from 5-day high
  const high5 = Math.max(...high.slice(Math.max(0, idx - 4), idx + 1));
  const drawdown = ((high5 - c) / high5) * 100;

  return {
    detected: true,
    rsi2: rsi2,
    rsi14: rsi14,
    extreme: extreme,
    three_day_decline: threeDayDecline,
    sma200: s200,
    sma5: s5,
    atr14: a14,
    stop: stop,
    exit_target_5sma: exitTarget5SMA,
    drawdown_from_5d_high: drawdown,
    reason: `RSI(2) = ${rsi2.toFixed(1)} ${extreme ? '(EXTREME ≤ 5)' : '(≤ 10)'} · above 200-SMA · ${drawdown.toFixed(1)}% off 5d high` +
            `${threeDayDecline ? ' · 3-day decline streak' : ''} · exit: close > 5-SMA (${s5.toFixed(2)}) or RSI(2) > 70`
  };
}

// ---------- Pocket Pivot (Kacher & Morales) ----------
// Up-day where volume exceeds the highest down-day volume of the prior 10 sessions.
// Stock must be near its 10-day or 50-day MA. SPY should be above 200-SMA (checked externally).
// Documented in "Trade Like an O'Neil Disciple" (2010). Win rate 55-65%.
function evaluatePocketPivot(bars, idx) {
  if (idx < 52) return { detected: false, reason: 'insufficient history' };
  const close = bars.map(b => b.close);
  const open_ = bars.map(b => b.open);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const vol   = bars.map(b => b.volume);
  const c = close[idx];

  // Must be an up-day (close > open)
  if (close[idx] <= open_[idx]) return { detected: false, reason: 'not an up day' };

  // Must be near 10-SMA or 50-SMA (within 3%)
  const s10 = sma(close, 10)[idx];
  const s50 = sma(close, 50)[idx];
  if (!s10 || !s50) return { detected: false, reason: 'SMA warmup' };
  const nearMA = Math.abs(c - s10) / s10 < 0.03 || Math.abs(c - s50) / s50 < 0.03;
  if (!nearMA) return { detected: false, reason: `not near 10/50-SMA (10=${s10.toFixed(2)}, 50=${s50.toFixed(2)})` };

  // Today's volume must exceed the highest down-day volume of the prior 10 sessions
  let maxDownVol = 0;
  for (let i = idx - 10; i < idx; i++) {
    if (i >= 0 && close[i] < open_[i]) maxDownVol = Math.max(maxDownVol, vol[i]);
  }
  if (maxDownVol === 0) return { detected: false, reason: 'no down days in prior 10 bars' };
  if (vol[idx] <= maxDownVol) return { detected: false, reason: `volume ${(vol[idx]/1e6).toFixed(1)}M <= max down-vol ${(maxDownVol/1e6).toFixed(1)}M` };

  // Must be above 50-SMA (uptrend context)
  if (c < s50) return { detected: false, reason: 'below 50-SMA' };

  const volRatio = vol[idx] / maxDownVol;
  const a14 = atr(high, low, close, 14)[idx];
  const stop = s10 < c ? s10 : c - 1.5 * (a14 || 0);

  return {
    detected: true,
    vol_ratio: volRatio,
    near_10sma: Math.abs(c - s10) / s10 < 0.03,
    near_50sma: Math.abs(c - s50) / s50 < 0.03,
    stop: stop,
    reason: `Pocket Pivot: vol ${(vol[idx]/1e6).toFixed(1)}M > max down-vol ${(maxDownVol/1e6).toFixed(1)}M (${volRatio.toFixed(1)}x) · near ${Math.abs(c-s10)/s10 < 0.03 ? '10' : '50'}-SMA`
  };
}

// ---------- High Tight Flag (O'Neil / CANSLIM) ----------
// Stock doubled (+100%) in <=8 weeks from a prior base, then forms tight consolidation <25%.
// Documented in "How to Make Money in Stocks". Win rate 65-75%. Extremely rare (0-3/year).
function evaluateHTF(bars, idx) {
  if (idx < 60) return { detected: false, reason: 'insufficient history' };
  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const c = close[idx];

  // Look for a 100%+ move in the last 8 weeks (40 trading days)
  // Find the lowest close in bars [idx-55 .. idx-15] as a potential base
  const searchStart = Math.max(0, idx - 55);
  const searchEnd = Math.max(0, idx - 15);
  let baseLow = Infinity, baseIdx = searchStart;
  for (let i = searchStart; i <= searchEnd; i++) {
    if (close[i] < baseLow) { baseLow = close[i]; baseIdx = i; }
  }

  // Find the peak after the base low
  let peak = 0, peakIdx = baseIdx;
  for (let i = baseIdx; i <= idx; i++) {
    if (high[i] > peak) { peak = high[i]; peakIdx = i; }
  }

  const moveUp = (peak - baseLow) / baseLow;
  if (moveUp < 1.0) return { detected: false, reason: `only +${(moveUp*100).toFixed(0)}% move (need +100%)` };

  // The move must have happened within 40 bars (8 weeks)
  if (peakIdx - baseIdx > 40) return { detected: false, reason: 'move took > 8 weeks' };

  // Now check for tight flag: from peak to current, pullback must be <25%
  let flagLow = Infinity;
  for (let i = peakIdx; i <= idx; i++) {
    flagLow = Math.min(flagLow, low[i]);
  }
  const flagDepth = (peak - flagLow) / peak;
  if (flagDepth > 0.25) return { detected: false, reason: `flag pullback ${(flagDepth*100).toFixed(0)}% > 25%` };

  // Flag must be at least 5 bars long (1 week of consolidation)
  if (idx - peakIdx < 5) return { detected: false, reason: 'flag too short (< 5 bars)' };

  // Current price should be within 10% of peak (still in the flag zone)
  if (c < peak * 0.75) return { detected: false, reason: 'price fell below flag zone' };

  const a14 = atr(high, low, close.slice(0, idx+1), 14).pop() || 0;
  const stop = flagLow * 0.99;
  const target = peak * 1.5; // HTF targets are typically 50-300% above breakout

  return {
    detected: true,
    move_pct: moveUp * 100,
    flag_depth_pct: flagDepth * 100,
    flag_bars: idx - peakIdx,
    peak: peak,
    flag_low: flagLow,
    stop: stop,
    target: target,
    reason: `HTF: +${(moveUp*100).toFixed(0)}% in ${peakIdx-baseIdx} bars · flag ${(flagDepth*100).toFixed(0)}% deep · ${idx-peakIdx} bars · pivot: ${peak.toFixed(2)}`
  };
}

// ---------- NR7 + Inside Day (Toby Crabel) ----------
// Today's range is the narrowest of the last 7 days AND today is an inside day.
// Signals imminent volatility expansion. Win rate 55-65% with trend filter.
function evaluateNR7(bars, idx) {
  if (idx < 10) return { detected: false, reason: 'insufficient history' };
  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);

  const todayRange = high[idx] - low[idx];

  // NR7: today's range is the narrowest of the last 7 days
  let isNR7 = true;
  for (let i = idx - 6; i < idx; i++) {
    if (i >= 0 && (high[i] - low[i]) <= todayRange) { isNR7 = false; break; }
  }
  if (!isNR7) return { detected: false, reason: 'not NR7 (not narrowest range of 7 days)' };

  // Inside day: high < yesterday's high AND low > yesterday's low
  const isInside = high[idx] < high[idx-1] && low[idx] > low[idx-1];
  if (!isInside) return { detected: false, reason: 'NR7 but not an inside day' };

  // Trend filter: above 50-SMA for directional bias (long)
  const s50 = sma(close, 50)[idx];
  const aboveTrend = s50 && close[idx] > s50;

  const buyStop = high[idx];
  const sellStop = low[idx];
  const a14 = atr(high, low, close, 14)[idx];

  return {
    detected: true,
    nr7_range: todayRange,
    inside_day: true,
    above_50sma: aboveTrend,
    buy_stop: buyStop,
    sell_stop: sellStop,
    atr14: a14,
    reason: `NR7+Inside: range ${todayRange.toFixed(2)} (narrowest of 7) · buy-stop > ${buyStop.toFixed(2)} · ${aboveTrend ? 'above 50-SMA (long bias)' : 'below 50-SMA (neutral)'}`
  };
}

// ---------- 52-Week High Breakout (Jegadeesh & Titman momentum) ----------
// Stock makes a new 52-week high on above-average volume.
// Academically validated momentum strategy. Win rate 60-65% at 3-6 month hold.
function evaluate52WH(bars, idx) {
  if (idx < 252) return { detected: false, reason: 'insufficient history (need 252 bars)' };
  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const vol   = bars.map(b => b.volume);
  const c = close[idx];

  // Find 52-week (252 trading days) high
  let high52w = 0;
  for (let i = idx - 251; i < idx; i++) {
    if (high[i] > high52w) high52w = high[i];
  }

  // Is today making a new 52w high?
  if (high[idx] <= high52w) return { detected: false, reason: `high ${high[idx].toFixed(2)} <= 52w high ${high52w.toFixed(2)}` };

  // Volume filter: today's volume > 20-day average
  const v20 = sma(vol, 20)[idx];
  if (!v20 || vol[idx] < v20) return { detected: false, reason: `volume below 20-day avg` };
  const volRatio = vol[idx] / v20;

  // Must be above 200-SMA (trend confirmation)
  const s200 = sma(close, 200)[idx];
  if (!s200 || c < s200) return { detected: false, reason: 'below 200-SMA' };

  const a14 = atr(high, bars.map(b=>b.low), close, 14)[idx];
  const stop = c - 2 * (a14 || 0);
  const strongBreakout = volRatio > 1.5;

  return {
    detected: true,
    high_52w: high52w,
    vol_ratio: volRatio,
    strong: strongBreakout,
    stop: stop,
    reason: `New 52w High: ${high[idx].toFixed(2)} > prior ${high52w.toFixed(2)} · vol ${volRatio.toFixed(1)}× avg${strongBreakout ? ' · STRONG breakout' : ''}`
  };
}

// ---------- Power Earnings Gap (Minervini / Zanger) ----------
// Gap up >=4% on >=2x average volume, price holds above gap open for 3+ days.
// OHLCV proxy for PEAD (Post-Earnings Announcement Drift). Win rate 65-72%.
function evaluatePEG(bars, idx) {
  if (idx < 25) return { detected: false, reason: 'insufficient history' };
  const close = bars.map(b => b.close);
  const open_ = bars.map(b => b.open);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const vol   = bars.map(b => b.volume);

  // Look for a gap-up event in the last 3-15 bars (we want the gap to have held)
  const v20 = sma(vol, 20);

  for (let lookback = 3; lookback <= 15; lookback++) {
    const gi = idx - lookback;
    if (gi < 1 || !v20[gi]) continue;

    const gapPct = (open_[gi] - close[gi-1]) / close[gi-1];
    if (gapPct < 0.04) continue; // need >= 4% gap up

    const volRatio = vol[gi] / v20[gi];
    if (volRatio < 2.0) continue; // need >= 2x avg volume

    // Check if gap has held: price never closed below the gap open for 3+ days
    const gapOpen = open_[gi];
    let gapHeld = true;
    let holdDays = 0;
    for (let d = gi; d <= idx; d++) {
      if (close[d] < gapOpen * 0.98) { gapHeld = false; break; } // 2% tolerance
      holdDays++;
    }
    if (!gapHeld || holdDays < 3) continue;

    // Current price should be near or pulling back to the gap open area (within 5% above)
    // or we're within 8% of the gap open level (pullback entry zone)
    const distFromGapOpen = (close[idx] - gapOpen) / gapOpen;
    const inPullbackZone = distFromGapOpen >= -0.02 && distFromGapOpen <= 0.08;

    // Also accept if it's still strong (within 3% of the post-gap high)
    let postGapHigh = 0;
    for (let d = gi; d <= idx; d++) postGapHigh = Math.max(postGapHigh, high[d]);
    const nearHigh = (postGapHigh - close[idx]) / postGapHigh < 0.03;

    if (!inPullbackZone && !nearHigh) continue;

    const a14 = atr(high, low, close, 14)[idx];
    const stop = gapOpen * 0.98; // gap must not fill

    return {
      detected: true,
      gap_pct: gapPct * 100,
      gap_vol_ratio: volRatio,
      gap_open: gapOpen,
      hold_days: holdDays,
      in_pullback: inPullbackZone,
      stop: stop,
      reason: `PEG: +${(gapPct*100).toFixed(1)}% gap on ${volRatio.toFixed(1)}× vol · held ${holdDays}d above ${gapOpen.toFixed(2)} · ${inPullbackZone ? 'pullback entry zone' : 'still strong'}`
    };
  }
  return { detected: false, reason: 'no qualifying gap event in last 15 bars' };
}

// ===================================================================
// FMP API-BASED STRATEGY HELPERS
// These use Financial Modeling Prep (https://financialmodelingprep.com)
// to fetch earnings surprise, insider trading, and analyst upgrade data.
// Requires a paid API key ($19/month for 300 calls/min).
// `fetchFMPData` lives in /src/data/fmp.js; the strategies below accept its
// result as a parameter so they stay pure.
// ===================================================================

// ---------- PEAD: Post-Earnings Announcement Drift ----------
// The most documented anomaly in finance. Stocks that beat earnings estimates by >5%
// drift in the surprise direction for 60+ days. Win rate: 75-80%.
// Documented by Ball & Brown (1968), Bernard & Thomas (1989), extensive academic literature.
function evaluatePEAD(fmpData, bars, idx) {
  if (!fmpData || !fmpData.earnings || fmpData.earnings.length === 0) {
    return { detected: false, reason: 'no FMP earnings data (need API key)' };
  }

  const close = bars.map(b => b.close);
  const today = bars[idx]?.date;
  if (!today) return { detected: false, reason: 'no date' };

  // Find the most recent earnings surprise within the last 60 trading days
  const recentEarnings = fmpData.earnings.filter(e => {
    if (!e.date) return false;
    // Compare dates (earnings are in YYYY-MM-DD format)
    const earnDate = e.date;
    // Find the bar index for this earnings date
    for (let i = Math.max(0, idx - 60); i <= idx; i++) {
      if (bars[i] && bars[i].date === earnDate) return true;
    }
    return false;
  });

  if (recentEarnings.length === 0) {
    return { detected: false, reason: 'no recent earnings (last 60 bars)' };
  }

  const latest = recentEarnings[0]; // FMP returns most recent first
  const actual = latest.actualEarningResult;
  const estimated = latest.estimatedEarning;

  if (actual == null || estimated == null || estimated === 0) {
    return { detected: false, reason: 'earnings data incomplete' };
  }

  const surprisePct = ((actual - estimated) / Math.abs(estimated)) * 100;

  // Positive surprise > 5% = bullish drift
  if (surprisePct < 5) {
    return { detected: false, reason: `earnings surprise only +${surprisePct.toFixed(1)}% (need >+5%)` };
  }

  // Must be above 200-SMA (quality filter)
  const s200 = sma(close, 200)[idx];
  if (s200 && close[idx] < s200) {
    return { detected: false, reason: 'beat earnings but below 200-SMA (trend broken)' };
  }

  // Find how many days since the earnings
  let daysSinceEarnings = 0;
  for (let i = idx; i >= Math.max(0, idx - 60); i--) {
    if (bars[i] && bars[i].date === latest.date) {
      daysSinceEarnings = idx - i;
      break;
    }
  }

  const strong = surprisePct > 15;  // Very strong beat
  const fresh = daysSinceEarnings <= 10; // Fresh = within 2 weeks

  return {
    detected: true,
    surprise_pct: surprisePct,
    actual: actual,
    estimated: estimated,
    days_since: daysSinceEarnings,
    strong: strong,
    fresh: fresh,
    earnings_date: latest.date,
    reason: `PEAD: +${surprisePct.toFixed(1)}% earnings surprise (${actual.toFixed(2)} vs est ${estimated.toFixed(2)}) · ${daysSinceEarnings}d ago${strong ? ' · STRONG beat' : ''}${fresh ? ' · FRESH' : ''}`
  };
}

// ---------- Insider Cluster Buy ----------
// When 3+ corporate insiders buy their own stock within 30 days, it's one of the
// strongest bullish signals. They have information advantages. Win rate: 65-75%.
// Documented by Lakonishok & Lee (2001), Seyhun (1986).
function evaluateInsiderCluster(fmpData, bars, idx) {
  if (!fmpData || !fmpData.insider || fmpData.insider.length === 0) {
    return { detected: false, reason: 'no FMP insider data (need API key)' };
  }

  const today = bars[idx]?.date;
  if (!today) return { detected: false, reason: 'no date' };

  // Parse today as a Date for comparison
  const todayDate = new Date(today + 'T00:00:00Z');
  const thirtyDaysAgo = new Date(todayDate.getTime() - 30 * 86400000);
  const ninetyDaysAgo = new Date(todayDate.getTime() - 90 * 86400000);

  // Filter for purchases (not sales, not options) within last 90 days
  const recentBuys = fmpData.insider.filter(t => {
    if (!t.transactionDate) return false;
    const td = new Date(t.transactionDate + 'T00:00:00Z');
    if (td < ninetyDaysAgo || td > todayDate) return false;
    // FMP uses "P-Purchase" or acquistionOrDisposition === "A" or transactionType includes "Purchase"
    const isPurchase = (t.acquistionOrDisposition === 'A') ||
                       (t.transactionType && t.transactionType.toLowerCase().includes('purchase'));
    return isPurchase;
  });

  // Count unique insiders who bought in the last 30 days
  const recentCluster = fmpData.insider.filter(t => {
    if (!t.transactionDate) return false;
    const td = new Date(t.transactionDate + 'T00:00:00Z');
    if (td < thirtyDaysAgo || td > todayDate) return false;
    const isPurchase = (t.acquistionOrDisposition === 'A') ||
                       (t.transactionType && t.transactionType.toLowerCase().includes('purchase'));
    return isPurchase;
  });

  const uniqueInsiders30d = new Set(recentCluster.map(t => t.reportingName || t.reportingCik || 'unknown'));
  const totalBuys90d = recentBuys.length;
  const clusterSize = uniqueInsiders30d.size;

  // Need at least 2 unique insiders buying in 30 days (cluster)
  if (clusterSize < 2) {
    return { detected: false, reason: `only ${clusterSize} insider buyer(s) in 30d (need ≥2)` };
  }

  // Calculate total $ bought
  const totalValue = recentCluster.reduce((sum, t) => sum + (t.securitiesTransacted || 0) * (t.price || 0), 0);

  const strong = clusterSize >= 3; // Strong cluster = 3+ insiders

  return {
    detected: true,
    cluster_size: clusterSize,
    total_buys_90d: totalBuys90d,
    total_value: totalValue,
    strong: strong,
    insiders: [...uniqueInsiders30d].slice(0, 5),
    reason: `Insider Cluster: ${clusterSize} unique insiders bought in 30d${strong ? ' (STRONG ≥3)' : ''} · $${(totalValue/1e6).toFixed(2)}M total · ${totalBuys90d} buys in 90d`
  };
}

// ---------- Analyst Upgrade Momentum ----------
// When a stock receives analyst upgrades (especially from "Hold" to "Buy" or "Outperform"),
// it tends to outperform for 1-3 months. Win rate: 60-70%.
// Documented by Womack (1996), Jegadeesh et al. (2004).
function evaluateAnalystUpgrade(fmpData, bars, idx) {
  if (!fmpData || !fmpData.upgrades || fmpData.upgrades.length === 0) {
    return { detected: false, reason: 'no FMP analyst data (need API key)' };
  }

  const today = bars[idx]?.date;
  if (!today) return { detected: false, reason: 'no date' };

  const todayDate = new Date(today + 'T00:00:00Z');
  const thirtyDaysAgo = new Date(todayDate.getTime() - 30 * 86400000);

  // Filter for upgrades in the last 30 days
  const recentUpgrades = fmpData.upgrades.filter(u => {
    if (!u.publishedDate) return false;
    const pd = new Date(u.publishedDate);
    if (pd < thirtyDaysAgo || pd > todayDate) return false;
    // Must be an upgrade (new grade > old grade in sentiment)
    const bullishGrades = ['buy', 'strong buy', 'outperform', 'overweight', 'positive', 'accumulate'];
    const neutralGrades = ['hold', 'neutral', 'equal-weight', 'market perform', 'sector perform', 'peer perform'];
    const newGrade = (u.newGrade || '').toLowerCase();
    const oldGrade = (u.previousGrade || '').toLowerCase();
    const newIsBullish = bullishGrades.some(g => newGrade.includes(g));
    const oldIsNeutralOrWorse = neutralGrades.some(g => oldGrade.includes(g)) ||
                                 oldGrade.includes('sell') || oldGrade.includes('underperform') ||
                                 oldGrade.includes('underweight') || oldGrade.includes('reduce');
    return newIsBullish && oldIsNeutralOrWorse;
  });

  // Also check for initiations at "Buy" or better
  const initiations = fmpData.upgrades.filter(u => {
    if (!u.publishedDate) return false;
    const pd = new Date(u.publishedDate);
    if (pd < thirtyDaysAgo || pd > todayDate) return false;
    const action = (u.action || '').toLowerCase();
    const newGrade = (u.newGrade || '').toLowerCase();
    const bullishGrades = ['buy', 'strong buy', 'outperform', 'overweight'];
    return action.includes('init') && bullishGrades.some(g => newGrade.includes(g));
  });

  const totalBullish = recentUpgrades.length + initiations.length;
  if (totalBullish === 0) {
    return { detected: false, reason: 'no recent upgrades/initiations in 30d' };
  }

  // Must be above 50-SMA (trend confirmation)
  const close = bars.map(b => b.close);
  const s50 = sma(close, 50)[idx];
  if (s50 && close[idx] < s50) {
    return { detected: false, reason: `upgraded but below 50-SMA (weak trend)` };
  }

  const firms = [...new Set([
    ...recentUpgrades.map(u => u.gradingCompany || 'Unknown'),
    ...initiations.map(u => u.gradingCompany || 'Unknown')
  ])];
  const strong = totalBullish >= 2; // Multiple upgrades = stronger

  return {
    detected: true,
    upgrade_count: recentUpgrades.length,
    initiation_count: initiations.length,
    total_bullish: totalBullish,
    firms: firms.slice(0, 5),
    strong: strong,
    reason: `Analyst: ${recentUpgrades.length} upgrade(s) + ${initiations.length} initiation(s) in 30d · ${firms.slice(0,3).join(', ')}${strong ? ' · MULTI-FIRM' : ''}`
  };
}

// ---------- Thematic Relative Strength score ----------
// Composite RS vs SPY across 1m / 3m / 6m windows. Stocks with the highest combined excess
// return are the "leaders within leaders" — the names that work in a thematic bull cycle.
function computeThematicRS(bars, spyBars, idx) {
  if (!spyBars || idx < 132 || idx >= spyBars.length) return null;
  const close = bars.map(b => b.close);
  const spyClose = spyBars.map(b => b.close);
  const windows = [21, 63, 126]; // 1m, 3m, 6m trading days
  let sum = 0, n = 0;
  const breakdown = {};
  for (const w of windows) {
    if (idx < w) continue;
    const stockRet = close[idx] / close[idx - w] - 1;
    const spyRet   = spyClose[idx] / spyClose[idx - w] - 1;
    const excess = stockRet - spyRet;
    sum += excess; n++;
    breakdown[`${w}d`] = { stock: stockRet, spy: spyRet, excess };
  }
  if (n === 0) return null;
  const avgExcess = sum / n;
  return {
    rs_score: avgExcess * 100,    // average excess return vs SPY across windows, in %
    breakdown,
    n_windows: n
  };
}

// ---------- Sector ranking ----------

function sectorRank(sectorBarsMap) {
  // sectorBarsMap = {XLK: [bars], XLV: [bars], ...}
  const rows = [];
  for (const [etf, bars] of Object.entries(sectorBarsMap)) {
    if (!bars || bars.length < 21) { rows.push({ etf, ret_20d: null, note: 'no data' }); continue; }
    const i = bars.length - 1;
    const ret = (bars[i].close / bars[i - 20].close) - 1;
    rows.push({ etf, ret_20d: ret });
  }
  rows.sort((a, b) => (b.ret_20d ?? -Infinity) - (a.ret_20d ?? -Infinity));
  rows.forEach((r, idx) => r.rank = idx + 1);
  return rows;
}

// ---------- Backtest engine ----------

function runBacktest(bars, spyBars, opts = {}) {
  // opts.equity        starting equity (default 100k)
  // opts.startIdx      first bar to evaluate (default 220 — indicator warmup)
  // opts.endIdx        last bar (default last bar)
  // opts.slippage_bps  per-side slippage in basis points (default 5 = 0.05%)
  // opts.commission    flat $ per side (default 1)
  // opts.trail         'chandelier' (default) | 'ema20' (legacy) — exit logic post first-target
  // opts.chandelier_atr_mult  ATR multiplier for chandelier (default 2.5)
  const equity0 = opts.equity ?? 100_000;
  const startIdx = opts.startIdx ?? 220;
  const endIdx = opts.endIdx ?? bars.length - 1;
  const slipBps = opts.slippage_bps ?? 5;
  const commission = opts.commission ?? 1;
  const trailMode = opts.trail ?? 'chandelier';
  const chandMult = opts.chandelier_atr_mult ?? 2.5;
  const slip = slipBps / 10_000;

  const trades = [];
  const equityCurve = [{ date: bars[startIdx].date, equity: equity0 }];
  let equity = equity0;
  let openTrade = null;

  const close = bars.map(b => b.close);
  const high  = bars.map(b => b.high);
  const low   = bars.map(b => b.low);
  const ema20 = ema(close, 20);
  const atr14 = atr(high, low, close, 14);

  // Realized PnL for a partial sell (applies sell-side slippage + commission)
  function bookSell(t, sharesSold, rawPx, dateLabel) {
    const fillPx = rawPx * (1 - slip);
    const grossPnl = (fillPx - t.entry) * sharesSold;
    equity += grossPnl - commission;
    t.legs = t.legs || [];
    t.legs.push({ date: dateLabel, shares: sharesSold, raw_price: rawPx, fill_price: fillPx, R: (fillPx - t.entry) / t.R_dollars_per_share });
  }

  function closeTrade(t, exitPx, exitDate, reason) {
    bookSell(t, t.shares, exitPx, exitDate);
    t.exit_date = exitDate;
    t.exit_price = exitPx * (1 - slip);
    t.exit_reason = reason;
    t.shares_remaining_at_exit = t.shares;
    // Final realized R = sum of leg R weighted by share fraction of original
    const totalR = t.legs.reduce((s, leg) => s + leg.R * (leg.shares / t.original_shares), 0);
    t.R_realized = totalR;
    trades.push(t);
  }

  for (let i = startIdx; i <= endIdx; i++) {
    // Manage open trade FIRST (today's bar)
    if (openTrade) {
      const t = openTrade;
      const todayOpen = bars[i].open, todayHigh = high[i], todayLow = low[i], todayClose = close[i];

      // Track high-water mark for chandelier trail
      if (todayHigh > t.highest_high_since_entry) t.highest_high_since_entry = todayHigh;

      // Stop hit intrabar — gap-down realism: if open is already through the stop, fill at open (worse)
      if (todayLow <= t.stop) {
        const rawExit = Math.min(t.stop, todayOpen);
        const reason = t.first_target_hit ? 'trail_stop' : (rawExit < t.stop ? 'gap_down_stop' : 'initial_stop');
        closeTrade(t, rawExit, bars[i].date, reason);
        openTrade = null;
      } else if (!t.first_target_hit && todayHigh >= t.target) {
        // Hit first target -> sell half, move stop to breakeven
        const halfShares = Math.max(1, Math.floor(t.shares / 2));
        const remaining = t.shares - halfShares;
        bookSell(t, halfShares, t.target, bars[i].date);
        t.first_target_hit_date = bars[i].date;
        t.first_target_hit = true;
        t.shares = remaining;
        t.stop = t.entry; // breakeven on the runner
        if (remaining === 0) {
          // Edge case: tiny position — close the trade now
          t.exit_date = bars[i].date;
          t.exit_price = t.target * (1 - slip);
          t.exit_reason = 'first_target_full';
          t.shares_remaining_at_exit = 0;
          t.R_realized = t.legs.reduce((s, leg) => s + leg.R * (leg.shares / t.original_shares), 0);
          trades.push(t);
          openTrade = null;
        }
      } else if (t.first_target_hit) {
        // Post-target trail
        if (trailMode === 'chandelier') {
          // Ratchet stop UP only — chandelier exit
          const a = atr14[i];
          if (a) {
            const trail = t.highest_high_since_entry - chandMult * a;
            if (trail > t.stop) t.stop = trail;
          }
          // Stop check happens on NEXT bar via the standard intrabar check
        } else if (trailMode === 'ema20') {
          // Legacy: exit on close < 20-EMA at next open
          if (todayClose < ema20[i] && i + 1 <= endIdx) {
            closeTrade(t, bars[i + 1].open, bars[i + 1].date, 'trail_20ema');
            openTrade = null;
          }
        }
      }

      // Time stop: 10 trading days since entry, exit on next open
      if (openTrade && (i - openTrade.entry_idx) >= 10 && i + 1 <= endIdx) {
        closeTrade(openTrade, bars[i + 1].open, bars[i + 1].date, 'time_stop_10d');
        openTrade = null;
      }
    }

    // Look for new entry on bar i (using bar i-1 as confirmation)
    if (!openTrade && i - 1 >= 220) {
      const evalRes = evaluateSetup(bars, spyBars, i - 1, opts.marketCfg || {});
      if (evalRes.confirmation_bar && evalRes.trade_plan) {
        const trigger = evalRes.trade_plan.entry_trigger;
        const todayOpen = bars[i].open;
        if (todayOpen > trigger * 1.010) {
          // gap > 1% — skip
        } else if (high[i] >= trigger) {
          // Stop-buy fills at MAX(trigger, open) — pre-slippage
          const rawFill = Math.max(trigger, todayOpen);
          const fill = rawFill * (1 + slip); // buy-side slippage
          const stop = fill - 1.5 * (evalRes.metrics.atr14);
          const target = fill + 2 * (fill - stop);
          const riskPerShare = fill - stop;
          const dollarsAtRisk = 0.0075 * equity;
          let shares = Math.floor(dollarsAtRisk / riskPerShare);
          const cashCap = 0.25 * equity;
          if (shares * fill > cashCap) shares = Math.floor(cashCap / fill);
          if (shares > 0) {
            equity -= commission; // entry commission
            openTrade = {
              entry_date: bars[i].date, entry_idx: i,
              entry: fill, raw_entry: rawFill,
              stop, target, initial_stop: stop,
              shares, original_shares: shares,
              R_dollars_per_share: riskPerShare,
              highest_high_since_entry: high[i],
              first_target_hit: false,
              setup_metrics: evalRes.metrics,
              legs: []
            };
          }
        }
      }
    }

    // Mark-to-market: include unrealized PnL on the runner so the equity curve is honest
    let mtm = equity;
    if (openTrade) mtm += (close[i] - openTrade.entry) * openTrade.shares;
    equityCurve.push({ date: bars[i].date, equity: mtm });
  }

  // Close any dangling trade at last bar (mark-to-close, with sell costs)
  if (openTrade) {
    closeTrade(openTrade, close[endIdx], bars[endIdx].date, 'eod_unwind');
    openTrade = null;
  }

  // Metrics
  const wins = trades.filter(t => t.R_realized > 0);
  const losses = trades.filter(t => t.R_realized <= 0);
  const winRate = trades.length ? wins.length / trades.length : 0;
  const avgWinR = wins.length ? wins.reduce((s, t) => s + t.R_realized, 0) / wins.length : 0;
  const avgLossR = losses.length ? losses.reduce((s, t) => s + t.R_realized, 0) / losses.length : 0;
  const expectancy = winRate * avgWinR - (1 - winRate) * Math.abs(avgLossR);
  const grossWinR = wins.reduce((s, t) => s + t.R_realized, 0);
  const grossLossR = Math.abs(losses.reduce((s, t) => s + t.R_realized, 0));
  const profitFactor = grossLossR > 0 ? grossWinR / grossLossR : (grossWinR > 0 ? Infinity : 0);

  // Max drawdown
  let peak = equity0, maxDD = 0;
  equityCurve.forEach(p => {
    if (p.equity > peak) peak = p.equity;
    const dd = (peak - p.equity) / peak;
    if (dd > maxDD) maxDD = dd;
  });

  return {
    final_equity: equity,
    pnl: equity - equity0,
    pnl_pct: (equity - equity0) / equity0,
    trades,
    equityCurve,
    metrics: {
      n_trades: trades.length, win_rate: winRate, avg_win_R: avgWinR, avg_loss_R: avgLossR,
      expectancy_R: expectancy, profit_factor: profitFactor, max_drawdown_pct: maxDD
    }
  };
}

// ---------- Portfolio backtest ----------
// Walks day-by-day across the entire watchlist, respecting:
//   - max concurrent positions
//   - max positions per sector
//   - portfolio heat cap (sum of open initial-stop risk)
//   - regime filter (SPY trend + VIX)
//   - sector rank filter (top-3 by 20d return)
// Uses the master SPY date timeline for alignment; per-ticker bars are looked up by date.
function runPortfolioBacktest(tickerBarsMap, tickerSectors, spyBars, sectorBarsMap, vixBars, opts = {}) {
  const equity0 = opts.equity ?? 100_000;
  const slip = (opts.slippage_bps ?? 5) / 10_000;
  const commission = opts.commission ?? 1;
  const maxPositions = opts.max_positions ?? 5;
  const maxPerSector = opts.max_per_sector ?? 2;
  const heatCapPct = opts.portfolio_heat_pct ?? 3.0;
  const riskPerTrade = opts.risk_per_trade ?? 0.0075;
  const cashCapPct = opts.cash_cap_pct ?? 0.25;
  const chandMult = opts.chandelier_atr_mult ?? 2.5;
  const startIdxOpt = opts.startIdx ?? 220;

  if (!spyBars || spyBars.length < 250) throw new Error('Portfolio backtest needs SPY history (run REFRESH first).');

  const dates = spyBars.map(b => b.date);
  const startIdx = Math.max(220, startIdxOpt);
  const endIdx = dates.length - 1;

  // Build per-ticker date→idx maps + pre-compute ATR series (for chandelier trail)
  const tickerIdx = {};
  for (const [t, bars] of Object.entries(tickerBarsMap)) {
    if (!bars || bars.error || bars.length < 220) continue;
    const m = new Map();
    bars.forEach((b, i) => m.set(b.date, i));
    const atrSeries = atr(bars.map(b=>b.high), bars.map(b=>b.low), bars.map(b=>b.close), 14);
    tickerIdx[t] = { bars, dateMap: m, atrSeries };
  }
  const sectorIdx = {};
  for (const [s, bars] of Object.entries(sectorBarsMap || {})) {
    if (!bars || bars.error) continue;
    const m = new Map();
    bars.forEach((b, i) => m.set(b.date, i));
    sectorIdx[s] = { bars, dateMap: m };
  }
  const vixMap = new Map();
  if (vixBars) vixBars.forEach((b, i) => vixMap.set(b.date, i));

  const spyClose = spyBars.map(b => b.close);
  const spy200 = sma(spyClose, 200);
  const spy50  = sma(spyClose,  50);

  let equity = equity0;
  const openTrades = [];
  const closedTrades = [];
  const equityCurve = [{ date: dates[startIdx], equity: equity0 }];
  const skipLog = [];

  function realizedR(t) {
    return t.legs.reduce((s, leg) =>
      s + ((leg.fill_price - t.entry) / t.R_dollars_per_share) * (leg.shares / t.original_shares), 0);
  }
  function closePosition(t, fillPx, exitDate, reason) {
    const fp = fillPx * (1 - slip);
    equity += (fp - t.entry) * t.shares - commission;
    t.legs.push({ date: exitDate, shares: t.shares, fill_price: fp });
    t.exit_date = exitDate; t.exit_price = fp; t.exit_reason = reason;
    t.shares_remaining_at_exit = t.shares;
    t.R_realized = realizedR(t);
    closedTrades.push(t);
  }

  for (let di = startIdx; di <= endIdx; di++) {
    const today = dates[di];

    // --- 1) Manage open positions
    for (let p = openTrades.length - 1; p >= 0; p--) {
      const t = openTrades[p];
      const info = tickerIdx[t.ticker];
      const tIdx = info.dateMap.get(today);
      if (tIdx == null) continue; // ticker didn't trade today (halt) — hold
      const bar = info.bars[tIdx];
      if (bar.high > t.highest_high_since_entry) t.highest_high_since_entry = bar.high;

      // Chandelier ratchet (only after first target hit)
      if (t.first_target_hit) {
        const a = info.atrSeries[tIdx];
        if (a) {
          const trail = t.highest_high_since_entry - chandMult * a;
          if (trail > t.stop) t.stop = trail;
        }
      }
      // Stop hit?
      if (bar.low <= t.stop) {
        const rawExit = Math.min(t.stop, bar.open);
        const reason = t.first_target_hit ? 'trail_stop' : (rawExit < t.stop ? 'gap_down_stop' : 'initial_stop');
        closePosition(t, rawExit, today, reason);
        openTrades.splice(p, 1);
        continue;
      }
      // First target?
      if (!t.first_target_hit && bar.high >= t.target) {
        const half = Math.max(1, Math.floor(t.shares / 2));
        const remaining = t.shares - half;
        const fp = t.target * (1 - slip);
        equity += (fp - t.entry) * half - commission;
        t.legs.push({ date: today, shares: half, fill_price: fp });
        t.first_target_hit = true; t.first_target_hit_date = today;
        t.shares = remaining; t.stop = t.entry; // breakeven on runner
        if (remaining === 0) {
          t.exit_date = today; t.exit_price = fp; t.exit_reason = 'first_target_full';
          t.R_realized = realizedR(t);
          closedTrades.push(t); openTrades.splice(p, 1);
          continue;
        }
      }
      // Time stop: 10 trading days
      if ((di - t.entry_di) >= 10) {
        const next = Math.min(di + 1, endIdx);
        const nextDate = dates[next];
        const nextTIdx = info.dateMap.get(nextDate);
        const fillPx = nextTIdx != null ? info.bars[nextTIdx].open : bar.close;
        closePosition(t, fillPx, nextDate, 'time_stop_10d');
        openTrades.splice(p, 1);
      }
    }

    // --- 2) Regime check (inline, cheap)
    const spyTrendOk = spyClose[di] > (spy200[di] || Infinity) && spyClose[di] > (spy50[di] || Infinity);
    const vixI = vixMap.get(today);
    const vixOk = vixI == null || vixBars[vixI].close < 25;
    const tradeable = spyTrendOk && vixOk;

    // --- 3) Look for new entries (only if tradeable + room)
    if (tradeable && openTrades.length < maxPositions) {
      // Today's sector ranks
      const sectRanks = [];
      for (const [s, sInfo] of Object.entries(sectorIdx)) {
        const sIdx = sInfo.dateMap.get(today);
        if (sIdx == null || sIdx < 20) continue;
        sectRanks.push({ s, ret: sInfo.bars[sIdx].close / sInfo.bars[sIdx - 20].close - 1 });
      }
      sectRanks.sort((a, b) => b.ret - a.ret);
      const top3 = new Set(sectRanks.slice(0, 3).map(r => r.s));

      const sectorCounts = {};
      openTrades.forEach(t => sectorCounts[t.sector] = (sectorCounts[t.sector] || 0) + 1);
      const heldTickers = new Set(openTrades.map(t => t.ticker));
      const currentHeat$ = openTrades.reduce((s, t) =>
        s + Math.max(0, (t.entry - t.stop) * t.shares), 0);

      // Find candidates with confirmed setup TODAY
      const candidates = [];
      for (const [ticker, info] of Object.entries(tickerIdx)) {
        if (heldTickers.has(ticker)) continue;
        const sec = tickerSectors[ticker];
        if (!top3.has(sec)) continue;
        if ((sectorCounts[sec] || 0) >= maxPerSector) continue;
        const tIdx = info.dateMap.get(today);
        if (tIdx == null || tIdx < 220) continue;
        const ev = evaluateSetup(info.bars, spyBars, tIdx, opts.marketCfg || {});
        if (!ev.confirmation_bar || !ev.trade_plan) continue;
        candidates.push({ ticker, sector: sec, ev, ret_1m: ev.metrics?.ret_1m ?? 0 });
      }
      candidates.sort((a, b) => b.ret_1m - a.ret_1m);

      // --- 4) Process entries on TOMORROW's open
      for (const c of candidates) {
        if (openTrades.length >= maxPositions) break;
        if ((sectorCounts[c.sector] || 0) >= maxPerSector) continue;
        if (di + 1 > endIdx) break;
        const tomorrow = dates[di + 1];
        const info = tickerIdx[c.ticker];
        const nextTIdx = info.dateMap.get(tomorrow);
        if (nextTIdx == null) continue;
        const nb = info.bars[nextTIdx];
        const trigger = c.ev.trade_plan.entry_trigger;
        if (nb.open > trigger * 1.01) { skipLog.push({ date: tomorrow, ticker: c.ticker, reason: 'gap > 1%' }); continue; }
        if (nb.high < trigger) continue; // didn't trigger
        const rawFill = Math.max(trigger, nb.open);
        const fill = rawFill * (1 + slip);
        const stop0 = fill - 1.5 * c.ev.metrics.atr14;
        const target = fill + 2 * (fill - stop0);
        const riskPS = fill - stop0;
        let shares = Math.floor((riskPerTrade * equity) / riskPS);
        const cashCap = cashCapPct * equity;
        if (shares * fill > cashCap) shares = Math.floor(cashCap / fill);
        if (shares <= 0) continue;
        // Heat check: would adding this push portfolio heat over cap?
        const newHeat$ = currentHeat$ + riskPS * shares;
        if ((newHeat$ / equity) * 100 > heatCapPct) {
          skipLog.push({ date: tomorrow, ticker: c.ticker, reason: `heat cap (${((newHeat$/equity)*100).toFixed(2)}% > ${heatCapPct}%)` });
          continue;
        }
        equity -= commission;
        openTrades.push({
          ticker: c.ticker, sector: c.sector,
          entry_date: tomorrow, entry_di: di + 1,
          entry: fill, raw_entry: rawFill,
          stop: stop0, initial_stop: stop0, target,
          shares, original_shares: shares,
          R_dollars_per_share: riskPS,
          highest_high_since_entry: nb.high,
          first_target_hit: false,
          legs: [],
          setup_metrics: c.ev.metrics
        });
        sectorCounts[c.sector] = (sectorCounts[c.sector] || 0) + 1;
      }
    }

    // --- 5) Mark to market (closed PnL + open positions at close)
    let mtm = equity;
    for (const t of openTrades) {
      const tIdx = tickerIdx[t.ticker].dateMap.get(today);
      if (tIdx != null) mtm += (tickerIdx[t.ticker].bars[tIdx].close - t.entry) * t.shares;
    }
    equityCurve.push({ date: today, equity: mtm });
  }

  // Close any dangling trades at last available bar
  for (const t of [...openTrades]) {
    const info = tickerIdx[t.ticker];
    const last = info.bars[info.bars.length - 1];
    closePosition(t, last.close, last.date, 'eod_unwind');
  }

  // Aggregate metrics
  const trades = closedTrades;
  const wins = trades.filter(t => t.R_realized > 0);
  const losses = trades.filter(t => t.R_realized <= 0);
  const winRate = trades.length ? wins.length / trades.length : 0;
  const grossW = wins.reduce((s, t) => s + t.R_realized, 0);
  const grossL = Math.abs(losses.reduce((s, t) => s + t.R_realized, 0));
  const expectancy = trades.length ? trades.reduce((s,t) => s + t.R_realized, 0) / trades.length : 0;
  const profitFactor = grossL > 0 ? grossW / grossL : (grossW > 0 ? Infinity : 0);
  let peak = equity0, maxDD = 0;
  equityCurve.forEach(p => { if (p.equity > peak) peak = p.equity; const dd = (peak - p.equity) / peak; if (dd > maxDD) maxDD = dd; });

  // Per-sector breakdown
  const bySector = {};
  trades.forEach(t => {
    const s = t.sector || 'UNK';
    if (!bySector[s]) bySector[s] = { n: 0, totalR: 0, wins: 0 };
    bySector[s].n++;
    bySector[s].totalR += t.R_realized;
    if (t.R_realized > 0) bySector[s].wins++;
  });

  // CAGR over the equity curve
  const years = (new Date(equityCurve[equityCurve.length - 1].date) - new Date(equityCurve[0].date)) / (365.25 * 86400000);
  const cagr = years > 0 ? Math.pow(equity / equity0, 1 / years) - 1 : 0;

  return {
    final_equity: equity, pnl: equity - equity0, pnl_pct: (equity - equity0) / equity0,
    trades, equityCurve, skipLog, bySector,
    metrics: {
      n_trades: trades.length, win_rate: winRate, expectancy_R: expectancy,
      profit_factor: profitFactor, max_drawdown_pct: maxDD,
      total_R: trades.reduce((s,t) => s + t.R_realized, 0),
      cagr
    }
  };
}

// ---------- Stooq CSV parser (browser fetch helper) ----------

function parseStooqCsv(text) {
  // CSV header: Date,Open,High,Low,Close,Volume
  const lines = text.trim().split(/\r?\n/);
  if (lines.length < 2) return [];
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',');
    if (parts.length < 6) continue;
    const [date, open, high, low, close, volume] = parts;
    if (!date || open === '' || open === 'null') continue;
    out.push({
      date,
      open: +open, high: +high, low: +low, close: +close,
      volume: +volume
    });
  }
  return out;
}

// =============================================================================
// PUBLIC EXPORTS
// =============================================================================

export {
  // Indicator primitives
  sma, ema, atr, rollingMax, rollingMin, rollingMean, rsi, pctReturn,
  // Core swing-pullback evaluator + regime
  evaluateSetup, regimeCheck,
  // Bullish FVG
  aggregateMonthly, findBullishFVGs, evaluateFVGRetest,
  // Per-ticker strategies
  evaluateQualityDip, evaluateVCP, evaluateRSI2MeanReversion,
  evaluatePocketPivot, evaluateHTF, evaluateNR7, evaluate52WH, evaluatePEG,
  // FMP-driven strategies (consumer modules pass in fmpData)
  evaluatePEAD, evaluateInsiderCluster, evaluateAnalystUpgrade,
  // Composites
  computeThematicRS, sectorRank,
  // Backtests
  runBacktest, runPortfolioBacktest,
  // CSV helper
  parseStooqCsv,
};
